name: "jwebcat"
description: "this is my first jekyll blog"

url: "http://localhost:4000"

paginate: 10

exclude: [sass]

markdown: redcarpet
permalink: pretty
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]